# Generated by Django 5.1 on 2026-06-25 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tpm", "0014_tpmgovernanceroledescription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_incident", models.DateField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LTI", "Lost Time Injury (LTI)"),
                            ("RWC", "Restricted Work Case (RWC)"),
                            ("MTC", "Medical Treatment Case (MTC)"),
                            ("FA", "First Aid (FA)"),
                            ("NM", "Near Miss (NM)"),
                        ],
                        default="FA",
                        max_length=10,
                    ),
                ),
                (
                    "unsafe_type",
                    models.CharField(
                        choices=[
                            ("UA", "Unsafe Act (UA)"),
                            ("UC", "Unsafe Condition (UC)"),
                            ("NONE", "None (Actual Incident)"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Material Handling", "Material Handling"),
                            ("Slip/Trip/Fall", "Slip/Trip/Fall"),
                            ("PPE Violation", "PPE Violation"),
                            ("Equipment Interaction", "Equipment Interaction"),
                            ("Fire Hazard", "Fire Hazard"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="incidents/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending Review"),
                            ("Investigation", "Under Investigation"),
                            ("Closed", "Closed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("investigation_findings", models.TextField(blank=True, default="")),
                ("closure_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capa_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_incidents",
                        to="tpm.capareport",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_incidents",
                        to="tpm.department",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_incident", "-created_at"],
            },
        ),
    ]
