# Generated by Django 5.1 on 2026-06-28 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tpm", "0014_tpmgovernanceroledescription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HODKPIUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="hod_kpi/uploads/%Y/%m/")),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("reporting_date", models.DateField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tpm.department"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "unique_together": {("department", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="HODKPIRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("PRODUCTION", "Production"),
                            ("QUALITY", "Quality"),
                            ("OEE", "OEE"),
                            ("SAFETY", "Safety"),
                            ("COST", "Cost"),
                        ],
                        max_length=20,
                    ),
                ),
                ("kpi_name", models.CharField(max_length=200)),
                ("uom", models.CharField(blank=True, max_length=50)),
                (
                    "view_type",
                    models.CharField(
                        choices=[
                            ("YTD", "Year to Date"),
                            ("MTD", "Month to Date"),
                            ("WTD", "Week to Date"),
                            ("NA", "Not Applicable"),
                        ],
                        default="NA",
                        max_length=5,
                    ),
                ),
                ("target", models.FloatField(blank=True, null=True)),
                ("actual", models.FloatField(blank=True, null=True)),
                ("achievement_pct", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GREEN", "Green"),
                            ("YELLOW", "Yellow"),
                            ("RED", "Red"),
                        ],
                        default="GREEN",
                        max_length=10,
                    ),
                ),
                ("is_below_target", models.BooleanField(default=False)),
                ("reason_deviation", models.TextField(blank=True, null=True)),
                ("root_cause", models.TextField(blank=True, null=True)),
                ("corrective_action", models.TextField(blank=True, null=True)),
                (
                    "responsible_owner",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="hod_kpi.hodkpiupload",
                    ),
                ),
            ],
            options={
                "ordering": ["domain", "kpi_name", "view_type"],
            },
        ),
        migrations.CreateModel(
            name="HODKPIDelayRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=300)),
                ("department_cause", models.CharField(blank=True, max_length=150)),
                ("duration_mins", models.FloatField(default=0.0)),
                ("contribution_pct", models.FloatField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delays",
                        to="hod_kpi.hodkpiupload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HODKPIMonthlySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted")],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("achievements", models.TextField(blank=True)),
                ("risks", models.TextField(blank=True)),
                ("support_required", models.TextField(blank=True)),
                ("resources_required", models.TextField(blank=True)),
                ("special_observations", models.TextField(blank=True)),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_recommendations", models.TextField(blank=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tpm.department"
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod_kpi.hodkpiupload",
                    ),
                ),
            ],
            options={
                "unique_together": {("department", "month", "year")},
            },
        ),
    ]
