# Generated by Django 5.1 on 2026-07-11 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tpm", "0020_oplsheet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SMEDRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "total_planned_time",
                    models.IntegerField(
                        default=0, help_text="Total planned duration in minutes"
                    ),
                ),
                (
                    "total_actual_time",
                    models.IntegerField(
                        default=0, help_text="Total actual duration in minutes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("In-LIMIT", "In-LIMIT"), ("BREACHED", "BREACHED")],
                        default="In-LIMIT",
                        max_length=50,
                    ),
                ),
                ("compliance_percentage", models.FloatField(default=0.0)),
                ("extra_time", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SMEDRunItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("start_time_planned", models.TimeField(blank=True, null=True)),
                ("finish_time_planned", models.TimeField(blank=True, null=True)),
                ("planned_duration", models.IntegerField(default=0)),
                ("start_time_actual", models.TimeField(blank=True, null=True)),
                ("finish_time_actual", models.TimeField(blank=True, null=True)),
                ("actual_duration", models.IntegerField(default=0)),
                (
                    "responsibility",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In-LIMIT", "In-LIMIT"),
                            ("BREACHED", "BREACHED"),
                            ("PENDING", "PENDING"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="smed.smedrun",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SMEDTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smed_templates",
                        to="tpm.department",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SMEDSubActivityConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        help_text="e.g. 'Pre Operational Activity of Delta & Shell Change'",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Furnace Power Off'", max_length=255
                    ),
                ),
                ("default_planned_duration_mins", models.IntegerField(default=0)),
                (
                    "default_responsibility",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_activities",
                        to="smed.smedtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="smedrun",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="smed.smedtemplate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="smedrun",
            unique_together={("template", "date")},
        ),
    ]
