# Generated by Django 5.1 on 2026-07-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smed", "0001_initial"),
        ("tpm", "0020_oplsheet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smedtemplate",
            name="code",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="smedtemplate",
            unique_together={("department", "code")},
        ),
    ]
