# Generated by Django 5.1 on 2026-06-09 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tpm", "0002_user_designation_user_employee_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "equipment_class",
                    models.CharField(
                        choices=[
                            ("A", "Class A (Critical)"),
                            ("B", "Class B (Important)"),
                        ],
                        max_length=2,
                    ),
                ),
                ("sap_code_mech", models.CharField(blank=True, max_length=30)),
                ("sap_code_elec", models.CharField(blank=True, max_length=30)),
                ("asset_cost", models.CharField(blank=True, max_length=50)),
                ("production_loss", models.CharField(blank=True, max_length=50)),
                ("rating_kw", models.FloatField(blank=True, null=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Weekly"),
                            ("FORTNIGHTLY", "Fortnightly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("BIMONTHLY", "Bi-Monthly"),
                        ],
                        max_length=15,
                    ),
                ),
                ("scheduled_days", models.CharField(blank=True, max_length=50)),
                ("category", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cmc_equipment",
                        to="tpm.department",
                    ),
                ),
            ],
            options={
                "ordering": ["department__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentBearingPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("bearing_no", models.CharField(blank=True, max_length=50)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bearing_points",
                        to="cmc.equipment",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="OilTestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("viscosity", models.FloatField(blank=True, null=True)),
                ("moisture", models.CharField(blank=True, max_length=50)),
                ("nas_class", models.CharField(blank=True, max_length=10)),
                ("test_no", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK")], max_length=10
                    ),
                ),
                ("notification_no", models.CharField(blank=True, max_length=50)),
                ("login_by", models.CharField(blank=True, max_length=20)),
                ("sent_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oil_tests",
                        to="cmc.equipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "equipment__name"],
            },
        ),
        migrations.CreateModel(
            name="PMScheduleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("actual_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DONE", "Completed"),
                            ("NR", "Not Running"),
                            ("SD", "Shutdown"),
                            ("NA", "Not Applicable"),
                            ("NP", "Not Approachable"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_entries",
                        to="cmc.equipment",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date"],
                "unique_together": {("equipment", "scheduled_date")},
            },
        ),
        migrations.CreateModel(
            name="VibrationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                (
                    "instrument",
                    models.CharField(
                        choices=[
                            ("ENPAC", "ENPAC"),
                            ("SKF", "SKF"),
                            ("CSI", "CSI"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("ROUTE", "Route"), ("ON_REQUEST", "On Request")],
                        default="ROUTE",
                        max_length=15,
                    ),
                ),
                ("stored_in", models.CharField(blank=True, max_length=100)),
                ("reported_through", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OK", "OK"),
                            ("NOT_OK", "Not OK"),
                            ("UM", "Under Monitoring (UM)"),
                            ("ATTENTION", "Need Attention"),
                        ],
                        max_length=15,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vibration_logs",
                        to="cmc.equipment",
                    ),
                ),
                (
                    "schedule_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vibration_log",
                        to="cmc.pmscheduleentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "equipment__name"],
            },
        ),
        migrations.CreateModel(
            name="VibrationReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bearing_label", models.CharField(max_length=100)),
                ("bearing_no", models.CharField(blank=True, max_length=50)),
                ("horizontal_r1", models.FloatField(blank=True, null=True)),
                ("vertical_r2", models.FloatField(blank=True, null=True)),
                ("axial", models.FloatField(blank=True, null=True)),
                ("unit", models.CharField(default="mm/s", max_length=20)),
                ("iso_limit", models.FloatField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "bearing_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cmc.equipmentbearingpoint",
                    ),
                ),
                (
                    "vibration_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="cmc.vibrationlog",
                    ),
                ),
            ],
            options={
                "ordering": ["bearing_point__sort_order"],
            },
        ),
        migrations.CreateModel(
            name="WDALog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("ratio", models.CharField(blank=True, max_length=20)),
                ("dl", models.FloatField(blank=True, null=True)),
                ("ds", models.FloatField(blank=True, null=True)),
                ("wpc", models.FloatField(blank=True, null=True)),
                ("slide", models.CharField(blank=True, max_length=50)),
                ("checked_by", models.CharField(blank=True, max_length=20)),
                (
                    "final_status",
                    models.CharField(
                        choices=[
                            ("OK", "OK"),
                            ("ATTENTION", "Need Attention"),
                            ("NOT_OK", "Not OK"),
                            ("NA", "Not Applicable"),
                        ],
                        max_length=15,
                    ),
                ),
                ("notification_no", models.CharField(blank=True, max_length=100)),
                ("sent_login", models.CharField(blank=True, max_length=20)),
                ("sent_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wda_logs",
                        to="cmc.equipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "equipment__name"],
            },
        ),
        migrations.CreateModel(
            name="SAPNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_no", models.CharField(max_length=50, unique=True)),
                ("raised_by", models.CharField(max_length=20)),
                ("raised_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("PENDING", "Pending Action"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("closed_date", models.DateField(blank=True, null=True)),
                ("action_taken", models.TextField(blank=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sap_notifications",
                        to="cmc.equipment",
                    ),
                ),
                (
                    "oil_test",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cmc.oiltestlog",
                    ),
                ),
                (
                    "vibration_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cmc.vibrationlog",
                    ),
                ),
                (
                    "wda_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cmc.wdalog",
                    ),
                ),
            ],
        ),
    ]
