# Generated by Django 5.1 on 2026-06-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="oiltestlog",
            name="test_type",
            field=models.CharField(
                choices=[("SCHEDULED", "As per Schedule"), ("ON_DEMAND", "On Demand")],
                default="SCHEDULED",
                max_length=15,
            ),
        ),
    ]
