# Generated by Django 5.1 on 2026-06-17 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmc", "0002_oiltestlog_test_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GreaseReportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "ferrocheck",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ferrocheck in PPM"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OK", "OK"), ("NOT_OK", "Not OK")], max_length=10
                    ),
                ),
                ("sent_date", models.DateField(blank=True, null=True)),
                ("login", models.CharField(blank=True, max_length=20)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grease_reports",
                        to="cmc.equipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "equipment__name"],
            },
        ),
        migrations.AddField(
            model_name="sapnotification",
            name="grease_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cmc.greasereportlog",
            ),
        ),
    ]
