# Generated by Django 5.1 on 2026-07-02 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tpm", "0015_kaizensheet_uploaded_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_no", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField()),
                (
                    "shift",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=5
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted")],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                (
                    "caster_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("grade", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "heat_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("inspected_qty", models.FloatField(default=0.0)),
                ("ftr_qty", models.FloatField(default=0.0)),
                (
                    "defect_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "defect_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "defect_severity",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("defect_qty", models.FloatField(default=0.0)),
                ("rejected_qty", models.FloatField(default=0.0)),
                ("reason_of_defect", models.TextField(blank=True, null=True)),
                (
                    "rework_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("rework_qty", models.FloatField(default=0.0)),
                ("reason_for_rework", models.TextField(blank=True, null=True)),
                (
                    "diversion_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("diversion_qty", models.FloatField(default=0.0)),
                ("reason_for_diversion", models.TextField(blank=True, null=True)),
                ("mix_grade", models.CharField(blank=True, max_length=100, null=True)),
                ("mix_qty", models.FloatField(default=0.0)),
                ("reason_for_mix_grade", models.TextField(blank=True, null=True)),
                ("por_type", models.CharField(blank=True, max_length=100, null=True)),
                ("por_qty", models.FloatField(default=0.0)),
                (
                    "por_doc_ref",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("por_remarks", models.TextField(blank=True, null=True)),
                ("accepted_qty", models.FloatField(default=0.0)),
                ("ftr_percent", models.FloatField(default=0.0)),
                (
                    "inspection_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("psfs_type", models.CharField(blank=True, max_length=100, null=True)),
                ("psfs_qty", models.FloatField(default=0.0)),
                ("reason_for_psfs", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="quality_attachments/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_entries",
                        to="tpm.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NonFTRReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("qty", models.FloatField(default=0.0)),
                (
                    "quality_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="non_ftr_reasons",
                        to="quality.qualityentry",
                    ),
                ),
            ],
        ),
    ]
