# Generated by Django 5.1 on 2026-07-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0002_qualityentry_section_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualityentry",
            name="shift",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C")],
                max_length=5,
                null=True,
            ),
        ),
    ]
