# Generated by Django 5.1 on 2026-06-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0002_user_designation_user_employee_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
