# Generated by Django 5.1 on 2026-06-10 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0003_user_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="KaizenSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pillar", models.CharField(max_length=10)),
                ("kaizen_no", models.CharField(blank=True, max_length=50)),
                ("activities", models.JSONField(blank=True, default=list)),
                ("loss_name", models.CharField(blank=True, max_length=255)),
                ("result_areas", models.JSONField(blank=True, default=list)),
                ("area_equipment", models.CharField(blank=True, max_length=255)),
                ("circle_name", models.CharField(blank=True, max_length=255)),
                ("theme", models.CharField(blank=True, max_length=255)),
                ("idea", models.TextField(blank=True)),
                ("benchmark", models.CharField(blank=True, max_length=255)),
                ("target", models.CharField(blank=True, max_length=255)),
                ("start_date", models.CharField(blank=True, max_length=50)),
                ("finish_date", models.CharField(blank=True, max_length=50)),
                ("team_leader", models.CharField(blank=True, max_length=100)),
                ("team_members", models.JSONField(blank=True, default=list)),
                (
                    "before_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="kaizen_images/"
                    ),
                ),
                (
                    "after_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="kaizen_images/"
                    ),
                ),
                ("tangible_benefits", models.JSONField(blank=True, default=list)),
                ("intangible_benefits", models.JSONField(blank=True, default=list)),
                ("analysis", models.TextField(blank=True)),
                ("result_text", models.TextField(blank=True)),
                (
                    "result_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="kaizen_images/"
                    ),
                ),
                ("horizontal_deployment", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kaizen_sheets",
                        to="tpm.department",
                    ),
                ),
            ],
        ),
    ]
