# Generated by Django 5.1 on 2026-06-10 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0004_kaizensheet"),
    ]

    operations = [
        migrations.CreateModel(
            name="CAPAReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_section", models.CharField(blank=True, max_length=255)),
                ("date_incident", models.CharField(blank=True, max_length=50)),
                ("capa_no", models.CharField(blank=True, max_length=50)),
                ("problem_what", models.TextField(blank=True)),
                ("problem_where", models.TextField(blank=True)),
                ("problem_when", models.TextField(blank=True)),
                ("problem_extent", models.TextField(blank=True)),
                ("breakdown_applicable", models.CharField(blank=True, max_length=50)),
                ("breakdown_hrs", models.CharField(blank=True, max_length=50)),
                ("breakdown_from", models.CharField(blank=True, max_length=50)),
                ("breakdown_to", models.CharField(blank=True, max_length=50)),
                ("responsible_team", models.JSONField(blank=True, default=list)),
                ("immediate_action", models.TextField(blank=True)),
                ("action_timeframe", models.CharField(blank=True, max_length=100)),
                ("action_responsibility", models.CharField(blank=True, max_length=100)),
                ("why_1", models.TextField(blank=True)),
                ("why_2", models.TextField(blank=True)),
                ("why_3", models.TextField(blank=True)),
                ("why_4", models.TextField(blank=True)),
                ("why_5", models.TextField(blank=True)),
                ("five_m_applicable", models.JSONField(blank=True, default=list)),
                ("conclusion", models.TextField(blank=True)),
                ("corrective_actions", models.JSONField(blank=True, default=list)),
                ("preventive_actions", models.JSONField(blank=True, default=list)),
                ("detailed_plan", models.TextField(blank=True)),
                ("modified_documents", models.JSONField(blank=True, default=list)),
                (
                    "modified_documents_other",
                    models.CharField(blank=True, max_length=255),
                ),
                ("training_details", models.TextField(blank=True)),
                ("date_implementation", models.CharField(blank=True, max_length=50)),
                ("effectiveness_evaluation", models.TextField(blank=True)),
                ("prepared_by", models.CharField(blank=True, max_length=100)),
                ("reviewed_by", models.CharField(blank=True, max_length=100)),
                ("approved_by", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capa_reports",
                        to="tpm.department",
                    ),
                ),
            ],
        ),
    ]
