# Generated by Django 5.1 on 2026-06-15 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0005_capareport"),
    ]

    operations = [
        migrations.AddField(
            model_name="capareport",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("In Progress", "In Progress"),
                    ("Closed", "Closed"),
                ],
                default="Open",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="CAPADocxUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("upload_date", models.DateField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_manual", models.BooleanField(default=False)),
                (
                    "key_contact",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("core_team", models.TextField(blank=True, default="")),
                ("objective", models.TextField(blank=True, default="")),
                ("ref_no", models.CharField(blank=True, default="", max_length=100)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capa_uploads",
                        to="tpm.department",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="capareport",
            name="docx_upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="tpm.capadocxupload",
            ),
        ),
    ]
