# Generated by Django 5.1 on 2026-06-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0006_capareport_status_capadocxupload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capareport",
            name="document_no",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="capareport",
            name="issue_date",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="capareport",
            name="issue_no",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
