# Generated by Django 5.1 on 2026-06-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0007_capareport_document_no_capareport_issue_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capareport",
            name="whys",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
