# Generated by Django 5.1 on 2026-06-16 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0008_capareport_whys"),
    ]

    operations = [
        migrations.CreateModel(
            name="TPMGovernanceAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_key",
                    models.CharField(
                        choices=[
                            ("sponsor", "Project Sponsor"),
                            ("chairman", "Steering Committee Chairman"),
                            ("vice_chairman", "Steering Committee Vice Chairman"),
                            ("committee_member", "Steering Committee Member"),
                            ("coordinator_pillar", "TPM Coordinator (Pillar)"),
                            ("coordinator_cell", "TPM Coordinator (Workstation/Cell)"),
                            ("hod", "HOD / Area Owner"),
                        ],
                        max_length=30,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="governance_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "unique_together": {("role_key", "user")},
            },
        ),
    ]
