# Generated by Django 5.1 on 2026-06-17 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0010_seed_governance_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomKPIDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pillar", models.CharField(max_length=10)),
                ("sl_no", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=300)),
                ("uom", models.CharField(blank=True, max_length=50)),
                ("benchmark", models.FloatField(blank=True, null=True)),
                ("target", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_kpi_definitions",
                        to="tpm.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom KPI Definition",
                "verbose_name_plural": "Custom KPI Definitions",
                "unique_together": {("department", "pillar", "sl_no")},
            },
        ),
    ]
