# Generated by Django 5.1 on 2026-06-18 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0011_customkpidefinition"),
    ]

    operations = [
        migrations.CreateModel(
            name="JHDepartmentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hod_name",
                    models.CharField(blank=True, default="Mr. ", max_length=150),
                ),
                (
                    "coordinator_name",
                    models.CharField(blank=True, default="Mr. ", max_length=150),
                ),
                ("plan_start_date", models.DateField(blank=True, null=True)),
                ("plan_end_date", models.DateField(blank=True, null=True)),
                (
                    "department",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jh_settings",
                        to="tpm.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JHMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_name", models.CharField(max_length=255)),
                ("no_of_equipment", models.IntegerField(default=1)),
                (
                    "rank",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C")],
                        default="A",
                        max_length=10,
                    ),
                ),
                (
                    "present_step",
                    models.CharField(
                        choices=[
                            ("Step 1", "Step 1"),
                            ("Step 2", "Step 2"),
                            ("Step 3", "Step 3"),
                            ("Step 4", "Step 4"),
                            ("Step 5", "Step 5"),
                            ("Step 6", "Step 6"),
                            ("Step 7", "Step 7"),
                        ],
                        default="Step 1",
                        max_length=20,
                    ),
                ),
                ("present_step_date", models.DateField(blank=True, null=True)),
                (
                    "circle_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "circle_leader",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jh_machines",
                        to="tpm.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JHMasterPlanCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.IntegerField()),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("week", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLAN", "PLAN"),
                            ("UNDER_PROGRESS", "UNDER PROGRESS"),
                            ("COMPLETED", "COMPLETED"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_cells",
                        to="tpm.jhmachine",
                    ),
                ),
            ],
            options={
                "unique_together": {("machine", "step", "year", "month", "week")},
            },
        ),
    ]
