# Generated by Django 5.1 on 2026-06-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0012_jhdepartmentsettings_jhmachine_jhmasterplancell"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
