# Generated by Django 5.1 on 2026-06-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0013_department_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="TPMGovernanceRoleDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_key", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=100)),
                ("designation", models.CharField(blank=True, max_length=200)),
                (
                    "responsibilities",
                    models.TextField(help_text="Responsibilities separated by newline"),
                ),
            ],
        ),
    ]
