# Generated by Django 5.1 on 2026-06-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0014_tpmgovernanceroledescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="kaizensheet",
            name="uploaded_file",
            field=models.FileField(blank=True, null=True, upload_to="kaizen_files/"),
        ),
    ]
