# Generated by Django 5.1 on 2026-07-08 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0015_kaizensheet_uploaded_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuguaiTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag_type",
                    models.CharField(
                        choices=[("RED", "Red Tag"), ("WHITE", "White Tag")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDENTIFIED", "Identified"),
                            ("RECTIFIED", "Rectified"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="fuguai_photos/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("logged_date", models.DateField(auto_now_add=True)),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuguai_tags",
                        to="tpm.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JHAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.IntegerField(
                        choices=[(1, "Step 1"), (2, "Step 2"), (3, "Step 3")]
                    ),
                ),
                ("audit_date", models.DateField(auto_now_add=True)),
                ("auditor_name", models.CharField(max_length=150)),
                ("score", models.FloatField()),
                (
                    "result",
                    models.CharField(
                        choices=[("PASSED", "Passed"), ("FAILED", "Failed")],
                        max_length=10,
                    ),
                ),
                ("checklist_answers", models.JSONField(blank=True, default=dict)),
                ("remarks", models.TextField(blank=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jh_audits",
                        to="tpm.department",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="tpm.jhmachine",
                    ),
                ),
            ],
            options={
                "verbose_name": "JH Step Audit",
                "verbose_name_plural": "JH Step Audits",
            },
        ),
        migrations.CreateModel(
            name="Trainee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("contact_number", models.CharField(max_length=20)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="trainee_photos/"
                    ),
                ),
                ("number_of_trainings", models.IntegerField(default=0)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainees",
                        to="tpm.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pillar", models.CharField(max_length=10)),
                ("training_date", models.DateField(auto_now_add=True)),
                ("topic", models.CharField(max_length=255)),
                ("remarks", models.TextField(blank=True)),
                (
                    "trainee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="tpm.trainee",
                    ),
                ),
            ],
        ),
    ]
