# Generated by Django 5.1 on 2026-07-08 11:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0016_fuguaitag_jhaudit_trainee_trainingsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuguaitag",
            name="actual_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fuguaitag",
            name="cause",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fuguaitag",
            name="classification",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="fuguaitag",
            name="countermeasure_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fuguaitag",
            name="date_of_detection",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="fuguaitag",
            name="detector_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="fuguaitag",
            name="executor_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="fuguaitag",
            name="hppt_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="fuguaitag",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tpm.jhmachine",
            ),
        ),
        migrations.AddField(
            model_name="fuguaitag",
            name="machine_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="fuguaitag",
            name="nos",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="fuguaitag",
            name="planned_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fuguaitag",
            name="shift",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C")], default="A", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="fuguaitag",
            name="sl_no",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fuguaitag",
            name="why_is_it_fuguai",
            field=models.TextField(blank=True),
        ),
    ]
