# Generated by Django 5.1 on 2026-07-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0017_fuguaitag_actual_completion_date_fuguaitag_cause_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fuguaitag",
            name="actual_completion_date",
        ),
        migrations.RemoveField(
            model_name="fuguaitag",
            name="cause",
        ),
        migrations.RemoveField(
            model_name="fuguaitag",
            name="classification",
        ),
        migrations.RemoveField(
            model_name="fuguaitag",
            name="countermeasure_content",
        ),
        migrations.RemoveField(
            model_name="fuguaitag",
            name="date_of_detection",
        ),
        migrations.RemoveField(
            model_name="fuguaitag",
            name="detector_name",
        ),
        migrations.RemoveField(
            model_name="fuguaitag",
            name="executor_name",
        ),
        migrations.RemoveField(
            model_name="fuguaitag",
            name="hppt_no",
        ),
        migrations.RemoveField(
            model_name="fuguaitag",
            name="machine",
        ),
        migrations.RemoveField(
            model_name="fuguaitag",
            name="machine_name",
        ),
        migrations.RemoveField(
            model_name="fuguaitag",
            name="nos",
        ),
        migrations.RemoveField(
            model_name="fuguaitag",
            name="planned_date",
        ),
        migrations.RemoveField(
            model_name="fuguaitag",
            name="shift",
        ),
        migrations.RemoveField(
            model_name="fuguaitag",
            name="sl_no",
        ),
        migrations.RemoveField(
            model_name="fuguaitag",
            name="why_is_it_fuguai",
        ),
    ]
