# Generated by Django 5.1 on 2026-07-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0018_remove_fuguaitag_actual_completion_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jhaudit",
            name="department",
        ),
        migrations.RemoveField(
            model_name="jhaudit",
            name="machine",
        ),
        migrations.RemoveField(
            model_name="trainee",
            name="department",
        ),
        migrations.RemoveField(
            model_name="trainingsession",
            name="trainee",
        ),
        migrations.DeleteModel(
            name="FuguaiTag",
        ),
        migrations.DeleteModel(
            name="JHAudit",
        ),
        migrations.DeleteModel(
            name="Trainee",
        ),
        migrations.DeleteModel(
            name="TrainingSession",
        ),
    ]
