# Generated by Django 5.1 on 2026-07-11 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0019_remove_jhaudit_department_remove_jhaudit_machine_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OPLSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pillar", models.CharField(max_length=10)),
                ("opl_no", models.CharField(blank=True, max_length=50)),
                ("theme", models.CharField(blank=True, max_length=255)),
                ("circle_name_members", models.CharField(blank=True, max_length=255)),
                ("lesson_type", models.CharField(default="basic", max_length=50)),
                (
                    "before_image",
                    models.ImageField(blank=True, null=True, upload_to="opl_images/"),
                ),
                (
                    "after_image",
                    models.ImageField(blank=True, null=True, upload_to="opl_images/"),
                ),
                ("benefits", models.TextField(blank=True)),
                ("prepared_by", models.CharField(blank=True, max_length=100)),
                ("verified_by", models.CharField(blank=True, max_length=100)),
                ("training_records", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opl_sheets",
                        to="tpm.department",
                    ),
                ),
            ],
        ),
    ]
