# Generated by Django 5.1 on 2026-07-15 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0021_oplsheet_uploaded_file_fuguairegister"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuguaiTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(blank=True, max_length=255)),
                (
                    "before_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="fuguai_images/"
                    ),
                ),
                (
                    "after_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="fuguai_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuguai_tags",
                        to="tpm.department",
                    ),
                ),
            ],
        ),
    ]
