# Generated by Django 5.1 on 2026-07-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0022_fuguaitag"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuguaitag",
            name="rectified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fuguaitag",
            name="tag_color",
            field=models.CharField(
                choices=[("WHITE", "White Tag"), ("RED", "Red Tag")],
                default="WHITE",
                max_length=10,
            ),
        ),
    ]
