# Generated by Django 5.1 on 2026-07-16 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpm", "0023_fuguaitag_rectified_at_fuguaitag_tag_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuguaitag",
            name="audit_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fuguaitag",
            name="audit_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Audit"),
                    ("OK", "OK (Correct)"),
                    ("REWORK", "Rework Required"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fuguaitag",
            name="audited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fuguaitag",
            name="audited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audited_fuguais",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
