# Generated by Django 5.1 on 2026-06-10 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tpm", "0003_user_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DelayUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/delays/"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        default="SUCCESS",
                        max_length=15,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delay_uploads",
                        to="tpm.department",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DelayRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(default="Manual Entry", max_length=100),
                ),
                ("date", models.DateField()),
                (
                    "time_slot",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '22:00 - 23:00'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "start_time",
                    models.CharField(
                        blank=True, help_text="e.g. '22:15'", max_length=50, null=True
                    ),
                ),
                (
                    "end_time",
                    models.CharField(
                        blank=True, help_text="e.g. '22:25'", max_length=50, null=True
                    ),
                ),
                (
                    "duration_mins",
                    models.FloatField(
                        default=0.0, help_text="Delay duration in minutes"
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        help_text="Responsible agency, e.g. 'Planned Delay', 'Mechanical'",
                        max_length=150,
                    ),
                ),
                (
                    "sub_agency",
                    models.CharField(
                        blank=True,
                        help_text="Sub-agency, e.g. 'Length change'",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="Rolled section, e.g. 'UC 254X254'",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True,
                        help_text="Equipment name or ID",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "sub_equipment",
                    models.CharField(
                        blank=True,
                        help_text="Sub equipment name or ID",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "shift_incharge",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the delay/breakdown"
                    ),
                ),
                (
                    "why",
                    models.TextField(
                        blank=True,
                        help_text="Root cause or 'why-why' analysis",
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delay_records",
                        to="tpm.department",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="delays.delayupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "start_time"],
            },
        ),
    ]
