# Generated by Django 5.1 on 2026-06-11 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0001_initial"),
        ("tpm", "0005_capareport"),
    ]

    operations = [
        migrations.CreateModel(
            name="DelayDropdownOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="e.g. 'Agency', 'Sub-Agency', 'Equipment', 'Sub-Equipment', etc.",
                        max_length=100,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "parent_value",
                    models.CharField(
                        blank=True,
                        help_text="Optional parent value, e.g. parent agency for a sub-agency",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delay_dropdown_options",
                        to="tpm.department",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "value"],
                "unique_together": {
                    ("department", "category", "value", "parent_value")
                },
            },
        ),
    ]
