# Generated by Django 5.1 on 2026-06-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0002_delaydropdownoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="delayrecord",
            name="is_locked",
            field=models.BooleanField(
                default=False, help_text="Whether this record is locked"
            ),
        ),
        migrations.AddField(
            model_name="delayupload",
            name="headers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Dynamic Excel headers mapped to fields",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="delayupload",
            name="is_locked",
            field=models.BooleanField(
                default=False, help_text="Whether this upload's records are locked"
            ),
        ),
    ]
