# Generated by Django 5.1 on 2026-06-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0003_delayrecord_is_locked_delayupload_headers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delayupload",
            name="headers",
        ),
        migrations.RemoveField(
            model_name="delayupload",
            name="is_locked",
        ),
        migrations.AlterField(
            model_name="delayrecord",
            name="is_locked",
            field=models.BooleanField(
                default=False, help_text="Locked records can only be edited by Admins"
            ),
        ),
    ]
