# Generated by Django 5.1 on 2026-06-17 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0004_remove_delayupload_headers_and_more"),
        ("tpm", "0011_customkpidefinition"),
    ]

    operations = [
        migrations.AddField(
            model_name="delayrecord",
            name="agency_type",
            field=models.CharField(
                choices=[("Internal", "Internal"), ("External", "External")],
                default="Internal",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="DelayNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delay_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delay_notifications",
                        to="delays.delayrecord",
                    ),
                ),
                (
                    "from_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_delay_notifications",
                        to="tpm.department",
                    ),
                ),
                (
                    "to_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_delay_notifications",
                        to="tpm.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
