# Generated by Django 5.1 on 2026-06-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0005_delayrecord_agency_type_delaynotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="delaynotification",
            name="response_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
