# Generated by Django 5.1 on 2026-07-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0006_delaynotification_response_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="delayrecord",
            name="production_loss",
            field=models.FloatField(
                blank=True, default=0.0, help_text="Production loss in Tons", null=True
            ),
        ),
    ]
