# Generated by Django 5.1 on 2026-07-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0007_delayrecord_production_loss"),
    ]

    operations = [
        migrations.AddField(
            model_name="delayrecord",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="End date of the delay/breakdown", null=True
            ),
        ),
    ]
