# Generated by Django 5.1 on 2026-07-03 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0008_delayrecord_end_date"),
        ("tpm", "0015_kaizensheet_uploaded_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentShutdownSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_area", models.CharField(max_length=255)),
                ("equipment", models.CharField(max_length=255)),
                ("shutdown_hrs", models.FloatField(default=0.0)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_shutdown_settings",
                        to="tpm.department",
                    ),
                ),
            ],
            options={
                "unique_together": {("department", "sub_area", "equipment")},
            },
        ),
    ]
