# Generated by Django 5.1 on 2026-07-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0009_equipmentshutdownsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="delayrecord",
            name="sub_area",
            field=models.CharField(
                blank=True, help_text="Sub-area", max_length=150, null=True
            ),
        ),
    ]
