# Generated by Django 5.1 on 2026-07-06 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0010_delayrecord_sub_area"),
        ("tpm", "0015_kaizensheet_uploaded_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("agency_type", models.CharField(default="Internal", max_length=50)),
                ("responsible_agency", models.CharField(max_length=150)),
                ("area", models.CharField(blank=True, max_length=150, null=True)),
                ("sub_area", models.CharField(blank=True, max_length=150, null=True)),
                ("equipment", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "sub_equipment",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "shift_incharge",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_checklists",
                        to="tpm.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_item", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("OK", "OK"), ("NOT OK", "NOT OK")], max_length=50
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="delays.maintenancechecklist",
                    ),
                ),
            ],
        ),
    ]
