# Generated by Django 5.1 on 2026-07-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0011_maintenancechecklist_maintenancechecklistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="delayrecord",
            name="action",
            field=models.TextField(
                blank=True, help_text="Action taken to resolve the delay", null=True
            ),
        ),
    ]
