# Generated by Django 5.1 on 2026-07-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0012_delayrecord_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancechecklist",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Fortnightly", "Fortnightly"),
                    ("Monthly", "Monthly"),
                    ("Quarterly", "Quarterly"),
                    ("Half Yearly", "Half Yearly"),
                    ("Yearly", "Yearly"),
                ],
                default="Daily",
                max_length=50,
            ),
        ),
    ]
