# Generated by Django 5.1 on 2026-07-09 07:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0013_maintenancechecklist_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancechecklist",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
