# Generated by Django 5.1 on 2026-07-10 05:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0014_alter_maintenancechecklist_date"),
        ("tpm", "0019_remove_jhaudit_department_remove_jhaudit_machine_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancechecklist",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="ChecklistSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checklist_name", models.CharField(max_length=255)),
                ("frequency", models.CharField(default="Daily", max_length=50)),
                (
                    "assigned_hod",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_checklists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_schedules",
                        to="tpm.department",
                    ),
                ),
            ],
            options={
                "unique_together": {("department", "checklist_name")},
            },
        ),
    ]
