# Generated by Django 5.1 on 2026-07-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0015_maintenancechecklist_created_at_checklistschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="delaydropdownoption",
            name="is_header",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="maintenancechecklist",
            name="engineer",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="maintenancechecklist",
            name="operator",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="maintenancechecklistitem",
            name="is_header",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="maintenancechecklistitem",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT OK", "NOT OK")],
                max_length=50,
                null=True,
            ),
        ),
    ]
