# Generated by Django 5.1 on 2026-07-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0016_delaydropdownoption_is_header_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancechecklist",
            name="remark",
            field=models.TextField(
                blank=True, help_text="General remark for the checklist", null=True
            ),
        ),
    ]
