# Generated by Django 5.1 on 2026-07-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0017_maintenancechecklist_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistschedule",
            name="shift_incharge",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
