# Generated by Django 5.1 on 2026-07-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0018_checklistschedule_shift_incharge"),
    ]

    operations = [
        migrations.AddField(
            model_name="delayrecord",
            name="has_production_loss",
            field=models.BooleanField(
                default=True,
                help_text="Flag to indicate if production loss calculation is enabled for this delay",
            ),
        ),
    ]
