# Generated by Django 5.1 on 2026-07-15 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0019_delayrecord_has_production_loss"),
        ("tpm", "0023_fuguaitag_rectified_at_fuguaitag_tag_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "plan_tap_sms2",
                    models.FloatField(default=0.0, verbose_name="Plan -TAP-SMS-2"),
                ),
                (
                    "plan_prod_sms",
                    models.FloatField(default=0.0, verbose_name="Plan -PROD.-SMS"),
                ),
                (
                    "plan_eaf2",
                    models.FloatField(default=0.0, verbose_name="Plan-EAF II"),
                ),
                (
                    "plan_prod_eaf2",
                    models.FloatField(default=0.0, verbose_name="Plan -PROD.-EAF II"),
                ),
                ("plan_neof", models.FloatField(default=0.0, verbose_name="Plan-NEOF")),
                (
                    "plan_prod_neof",
                    models.FloatField(default=0.0, verbose_name="Plan-PROD.-NEOF"),
                ),
                (
                    "actual_tap_sms2",
                    models.FloatField(default=0.0, verbose_name="Actual -TAP-SMS-2"),
                ),
                (
                    "actual_prod_sms",
                    models.FloatField(default=0.0, verbose_name="Actual- PROD.-SMS"),
                ),
                (
                    "actual_eaf2",
                    models.FloatField(default=0.0, verbose_name="Actual-EAF II"),
                ),
                (
                    "actual_prod_eaf2",
                    models.FloatField(
                        default=0.0, verbose_name="Actual - PROD.-EAF II"
                    ),
                ),
                (
                    "actual_neof",
                    models.FloatField(default=0.0, verbose_name="Actual- NEOF"),
                ),
                (
                    "actual_prod_neof",
                    models.FloatField(default=0.0, verbose_name="Actual- PROD.- NEOF"),
                ),
                (
                    "prod_loss_nof",
                    models.FloatField(
                        default=0.0, verbose_name="Production Loss (MTs) (NOF)"
                    ),
                ),
                (
                    "prod_loss_eaf2",
                    models.FloatField(
                        default=0.0, verbose_name="Production Loss (MTs) (EAF II)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_records",
                        to="tpm.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("department", "date")},
            },
        ),
    ]
