# Generated by Django 5.1 on 2026-07-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delays", "0020_performancerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancerecord",
            name="actual_eaf3_heats",
            field=models.FloatField(
                default=0.0, verbose_name="Actual -EAF III (Heat Nos)"
            ),
        ),
        migrations.AddField(
            model_name="performancerecord",
            name="actual_prod_eaf3",
            field=models.FloatField(default=0.0, verbose_name="Actual -PROD.-EAF III"),
        ),
        migrations.AddField(
            model_name="performancerecord",
            name="plan_eaf3_heats",
            field=models.FloatField(
                default=0.0, verbose_name="Plan -EAF III (Heat Nos)"
            ),
        ),
        migrations.AddField(
            model_name="performancerecord",
            name="plan_prod_eaf3",
            field=models.FloatField(default=0.0, verbose_name="Plan-PROD.-EAF III"),
        ),
        migrations.AddField(
            model_name="performancerecord",
            name="prod_loss_eaf3",
            field=models.FloatField(
                default=0.0, verbose_name="Production Loss (MTs) (EAF III)"
            ),
        ),
    ]
