# Generated by Django 5.1 on 2026-06-12 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tpm", "0005_capareport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FMEARecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("identification_date", models.DateField(blank=True, null=True)),
                (
                    "risk_owner",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("as_on_date", models.DateField(blank=True, null=True)),
                ("status_remarks", models.TextField(blank=True, default="")),
                ("sn", models.CharField(blank=True, default="", max_length=50)),
                (
                    "main_equipment",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("main_equipment_function", models.TextField(blank=True, default="")),
                ("functional_failure", models.TextField(blank=True, default="")),
                (
                    "sub_equipment",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("component", models.CharField(blank=True, default="", max_length=150)),
                ("component_function", models.TextField(blank=True, default="")),
                ("potential_failure_mode", models.TextField(blank=True, default="")),
                ("potential_effects", models.TextField(blank=True, default="")),
                ("severity", models.IntegerField(default=1)),
                ("potential_causes", models.TextField(blank=True, default="")),
                ("occurrence", models.IntegerField(default=1)),
                ("current_controls", models.TextField(blank=True, default="")),
                ("recommended_actions", models.TextField(blank=True, default="")),
                ("detection", models.IntegerField(default=1)),
                ("rpn", models.IntegerField(default=1)),
                ("contingency_plan", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(blank=True, default="Not Started", max_length=50),
                ),
                ("action_taken", models.TextField(blank=True, default="")),
                ("action_severity", models.IntegerField(blank=True, null=True)),
                ("action_occurrence", models.IntegerField(blank=True, null=True)),
                ("action_detection", models.IntegerField(blank=True, null=True)),
                ("action_rpn", models.IntegerField(blank=True, null=True)),
                ("mitigation_q1", models.TextField(blank=True, default="[]")),
                ("mitigation_q2", models.TextField(blank=True, default="[]")),
                ("mitigation_q3", models.TextField(blank=True, default="[]")),
                ("mitigation_q4", models.TextField(blank=True, default="[]")),
                ("mitigation_q1_target", models.DateField(blank=True, null=True)),
                ("mitigation_q2_target", models.DateField(blank=True, null=True)),
                ("mitigation_q3_target", models.DateField(blank=True, null=True)),
                ("mitigation_q4_target", models.DateField(blank=True, null=True)),
                (
                    "mitigation_q1_status",
                    models.CharField(blank=True, default="Not Started", max_length=30),
                ),
                (
                    "mitigation_q2_status",
                    models.CharField(blank=True, default="Not Started", max_length=30),
                ),
                (
                    "mitigation_q3_status",
                    models.CharField(blank=True, default="Not Started", max_length=30),
                ),
                (
                    "mitigation_q4_status",
                    models.CharField(blank=True, default="Not Started", max_length=30),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fmea_records",
                        to="tpm.department",
                    ),
                ),
            ],
            options={
                "ordering": ["sn", "id"],
            },
        ),
        migrations.CreateModel(
            name="FMEAAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("details", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="fmea.fmearecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
