# Generated by Django 5.1 on 2026-06-13 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fmea", "0002_fmeaexcelupload_fmearecord_excel_upload"),
        ("tpm", "0005_capareport"),
    ]

    operations = [
        migrations.CreateModel(
            name="FMEACriticalSpare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spare_description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("qty", models.CharField(blank=True, default="", max_length=50)),
                ("remarks_1", models.TextField(blank=True, default="")),
                ("lead_time", models.CharField(blank=True, default="", max_length=100)),
                ("remarks_2", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="critical_spares",
                        to="tpm.department",
                    ),
                ),
                (
                    "excel_upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="critical_spares",
                        to="fmea.fmeaexcelupload",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
