# Generated by Django 5.1 on 2026-06-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fmea", "0003_fmeacriticalspare"),
    ]

    operations = [
        migrations.AddField(
            model_name="fmeaexcelupload",
            name="is_manual",
            field=models.BooleanField(default=False),
        ),
    ]
