# Generated by Django 5.1 on 2026-06-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fmea", "0004_fmeaexcelupload_is_manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="fmearecord",
            name="action_plan_data",
            field=models.TextField(blank=True, default="[]"),
        ),
    ]
